modLoader="javafml"
loaderVersion="[41,)"
license="MIT Lisence"
[[mods]]
modId="abundant_atmosphere"
version="${0.2-1.19.2}"
displayName="Abundant Atmosphere"
logoFile="logo.png"
credits="Sheddmer, Probeyes, Umpaz"
authors="Sheddmer"
description='''
WIP
'''
[[dependencies.abundant_atmosphere]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.abundant_atmosphere]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.abundant_atmosphere]]
modId = "blueprint"
mandatory = true
versionRange = "[6.1.0,)"
ordering = "BEFORE"
side = "BOTH"