modLoader="javafml"
loaderVersion="[41,)"
license="MIT Lisence"
[[mods]]
modId="abundant_atmosphere"
version="${1.0.1-1.19.2}"
displayName="Abundant Atmosphere"
logoFile="logo.png"
credits="Sheddmer, Probeyes, Umpaz"
authors="Sheddmer"
description='''
Abundant Atmosphere is a bite sized mod that introduces different decorative blocks and small additions that are made to generally expand and somewhat improve the overworld. There are also some changes to existing structures, so far the ancient city, and there will be additional structures being added into the world to overall make exploration more fun and give you different challenges, with unique rewards.
'''
[[dependencies.abundant_atmosphere]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.abundant_atmosphere]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.abundant_atmosphere]]
modId = "blueprint"
mandatory = true
versionRange = "[6.1.0,)"
ordering = "BEFORE"
side = "BOTH"